### PR TITLE
Feature/start end toggle

### PR DESCRIPTION
**Pull request by garyjlin**
1. Added toggle for start/end date selection
2. Added disabled days support

calendarstartend

### CODE REVIEW

**Comment by zuqini** [comment]
How come does everything looks slightly more transparent? And the bug where the ranges overlap each other is back

**Comment by garyjlin** [comment]
Ah, any day that's transparent is "disabled". Also, what's the range overlap bug?

**Comment by zuqini** [comment]
screen shot 2017-04-19 at 9 27 23 pm
borders overlapping each other.

Pretty sure the range styling is also transparent now.

**Comment by garyjlin** [comment]
@zuqini My bad, turns out I checked in an older version of styles.js. How is it now?

**Review by zuqini — APPROVED** [review]
looks good now. 👍

**Comment by garyjlin** [comment]
Updated View: 

screen shot 2017-04-19 at 11 26 02 pm

**Pull request merged**
